//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzaStore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show on start up.
        /// </summary>
        public static string Alwaysshowonstartup {
            get {
                return ResourceManager.GetString("Alwaysshowonstartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PizzaStore.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Pizzas.
        /// </summary>
        public static string AvailablePizzas {
            get {
                return ResourceManager.GetString("AvailablePizzas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel&amp;Order.
        /// </summary>
        public static string CancelOrder {
            get {
                return ResourceManager.GetString("CancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Ingredients.
        /// </summary>
        public static string CurrentIngredients {
            get {
                return ResourceManager.GetString("CurrentIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Address:.
        /// </summary>
        public static string CustomerAddress {
            get {
                return ResourceManager.GetString("CustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Email:.
        /// </summary>
        public static string CustomerEmail {
            get {
                return ResourceManager.GetString("CustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer First Name:.
        /// </summary>
        public static string CustomerFirstName {
            get {
                return ResourceManager.GetString("CustomerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Last Name:.
        /// </summary>
        public static string CustomerLastName {
            get {
                return ResourceManager.GetString("CustomerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Phone:.
        /// </summary>
        public static string CustomerPhone {
            get {
                return ResourceManager.GetString("CustomerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Customer Value.
        /// </summary>
        public static string DefaultCustomerValue {
            get {
                return ResourceManager.GetString("DefaultCustomerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Ingredient Value.
        /// </summary>
        public static string DefaultIngredientValue {
            get {
                return ResourceManager.GetString("DefaultIngredientValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Pizza Value.
        /// </summary>
        public static string DefaultPizzaValue {
            get {
                return ResourceManager.GetString("DefaultPizzaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Options.
        /// </summary>
        public static string ImageOptions {
            get {
                return ResourceManager.GetString("ImageOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient.
        /// </summary>
        public static string Ingredient {
            get {
                return ResourceManager.GetString("Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Images.
        /// </summary>
        public static string IngredientImages {
            get {
                return ResourceManager.GetString("IngredientImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Info.
        /// </summary>
        public static string IngredientInfo {
            get {
                return ResourceManager.GetString("IngredientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Name.
        /// </summary>
        public static string IngredientName {
            get {
                return ResourceManager.GetString("IngredientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Price.
        /// </summary>
        public static string IngredientPrice {
            get {
                return ResourceManager.GetString("IngredientPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This App is made for
        ///creating Ingredients and Pizzas
        ///Handling Pizza Orders from Customers!.
        /// </summary>
        public static string IntroductionText {
            get {
                return ResourceManager.GetString("IntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Restart Needed Info.
        /// </summary>
        public static string NotifyRestartNeededInfo {
            get {
                return ResourceManager.GetString("NotifyRestartNeededInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date:.
        /// </summary>
        public static string Order_Date {
            get {
                return ResourceManager.GetString("Order Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Price:.
        /// </summary>
        public static string Order_Price_ {
            get {
                return ResourceManager.GetString("Order Price:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date:.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order History.
        /// </summary>
        public static string OrderHistory {
            get {
                return ResourceManager.GetString("OrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID:.
        /// </summary>
        public static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Info.
        /// </summary>
        public static string OrderInfo {
            get {
                return ResourceManager.GetString("OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Must Have Customer Name.
        /// </summary>
        public static string OrderMustHaveCustomerName {
            get {
                return ResourceManager.GetString("OrderMustHaveCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order PayStatus:.
        /// </summary>
        public static string OrderPayStatus {
            get {
                return ResourceManager.GetString("OrderPayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Price:.
        /// </summary>
        public static string OrderPrice {
            get {
                return ResourceManager.GetString("OrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Time:.
        /// </summary>
        public static string OrderTime {
            get {
                return ResourceManager.GetString("OrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza.
        /// </summary>
        public static string Pizza {
            get {
                return ResourceManager.GetString("Pizza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza Images.
        /// </summary>
        public static string PizzaImages {
            get {
                return ResourceManager.GetString("PizzaImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza Info.
        /// </summary>
        public static string PizzaInfo {
            get {
                return ResourceManager.GetString("PizzaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza List.
        /// </summary>
        public static string PizzaList {
            get {
                return ResourceManager.GetString("PizzaList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza Name.
        /// </summary>
        public static string PizzaName {
            get {
                return ResourceManager.GetString("PizzaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizzas.
        /// </summary>
        public static string Pizzas {
            get {
                return ResourceManager.GetString("Pizzas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza Size.
        /// </summary>
        public static string PizzaSize {
            get {
                return ResourceManager.GetString("PizzaSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza Size-Price Unit.
        /// </summary>
        public static string PizzaSizePriceUnit {
            get {
                return ResourceManager.GetString("PizzaSizePriceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Info After Order.
        /// </summary>
        public static string RefreshInfoAfterOrder {
            get {
                return ResourceManager.GetString("RefreshInfoAfterOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Welcome On StartUp.
        /// </summary>
        public static string ShowWelcomeOnStartUp {
            get {
                return ResourceManager.GetString("ShowWelcomeOnStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size-Price Unit.
        /// </summary>
        public static string SizePriceUnit {
            get {
                return ResourceManager.GetString("SizePriceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Time:.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TakeOrder.
        /// </summary>
        public static string TakeOrder {
            get {
                return ResourceManager.GetString("TakeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Order ( Customer Info ).
        /// </summary>
        public static string TheOrderCustomerInfo {
            get {
                return ResourceManager.GetString("TheOrderCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Order ( Pizzas ).
        /// </summary>
        public static string TheOrderPizzas {
            get {
                return ResourceManager.GetString("TheOrderPizzas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalPrice.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Pizza Store.
        /// </summary>
        public static string WelcomeToPizzaStore {
            get {
                return ResourceManager.GetString("WelcomeToPizzaStore", resourceCulture);
            }
        }
    }
}
